services:
  eureka:
    image: ygqygq2/eureka-server:latest
    container_name: eureka
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8761/"]
      interval: 10s
      timeout: 2s
      retries: 10
    restart: unless-stopped
