image:
  repository: ghcr.io/<tu-org>/<tu-repo>/api-gateway
  tag: latest

resources:
  requests: { cpu: "100m", memory: "128Mi" }
  limits:   { cpu: "300m", memory: "256Mi" }

# Inyecta config global y secretos
envFrom:
  - configMapRef: { name: app-config }
  - secretRef:    { name: app-secrets }

# Variables específicas del servicio
env:
  - name: EUREKA_URI
    value: "http://eureka.fuelhub.svc.cluster.local:8761/eureka" # ajusta si usas otro nombre
  - name: RABBITMQ_URL
    value: "amqp://guest:guest@rabbitmq.fuelhub.svc.cluster.local:5672"

service:
  port: 8080

ingress:
  enabled: true
  hosts:
    - host: gateway.<TU-DNS>.cloudapp.azure.com
      paths:
        - path: /
          pathType: Prefix
