apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fuel-system.fullname" . }}-config
  labels:
    {{- include "fuel-system.labels" . | nindent 4 }}
data:
  EUREKA_HOST: {{ include "fuel-system.eureka.host" . | quote }}
  EUREKA_PORT: "8761"
  POSTGRESQL_HOST: {{ include "fuel-system.postgresql.host" . | quote }}
  POSTGRESQL_PORT: "5432"
  RABBITMQ_HOST: {{ include "fuel-system.rabbitmq.host" . | quote }}
  RABBITMQ_PORT: "5672"
  ELASTICSEARCH_HOST: {{ include "fuel-system.elasticsearch.host" . | quote }}
  ELASTICSEARCH_PORT: "9200"
  NODE_ENV: "production"

