apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fuel-system.fullname" . }}-postgresql
  labels:
    {{- include "fuel-system.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.secrets.postgresql.username | b64enc | quote }}
  password: {{ .Values.secrets.postgresql.password | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fuel-system.fullname" . }}-rabbitmq
  labels:
    {{- include "fuel-system.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.secrets.rabbitmq.username | b64enc | quote }}
  password: {{ .Values.secrets.rabbitmq.password | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fuel-system.fullname" . }}-jwt
  labels:
    {{- include "fuel-system.labels" . | nindent 4 }}
type: Opaque
data:
  secret: {{ .Values.secrets.jwt.secret | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fuel-system.fullname" . }}-smtp
  labels:
    {{- include "fuel-system.labels" . | nindent 4 }}
type: Opaque
data:
  host: {{ .Values.secrets.smtp.host | b64enc | quote }}
  port: {{ .Values.secrets.smtp.port | toString | b64enc | quote }}
  user: {{ .Values.secrets.smtp.user | b64enc | quote }}
  password: {{ .Values.secrets.smtp.password | b64enc | quote }}

