{{/* ===================== PostgreSQL ===================== */}}
{{- if not .Values.postgresql.enabled }}
{{- $pgName := printf "%s-postgresql" (include "fuel-system.fullname" .) -}}
{{- $pgExisting := (lookup "v1" "Secret" .Release.Namespace $pgName) -}}
{{- if not $pgExisting }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $pgName }}
  labels:
    {{- include "fuel-system.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.secrets.postgresql.username | b64enc | quote }}
  password: {{ .Values.secrets.postgresql.password | b64enc | quote }}
{{- end }}
{{- end }}

---
{{/* ====================== RabbitMQ ====================== */}}
{{- if not .Values.rabbitmq.enabled }}
{{- $rmqName := printf "%s-rabbitmq" (include "fuel-system.fullname" .) -}}
{{- $rmqExisting := (lookup "v1" "Secret" .Release.Namespace $rmqName) -}}
{{- if not $rmqExisting }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $rmqName }}
  labels:
    {{- include "fuel-system.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.secrets.rabbitmq.username | b64enc | quote }}
  password: {{ .Values.secrets.rabbitmq.password | b64enc | quote }}
{{- end }}
{{- end }}

---
{{/* ======================== JWT ========================= */}}
{{- $jwtName := printf "%s-jwt" (include "fuel-system.fullname" .) -}}
{{- $jwtExisting := (lookup "v1" "Secret" .Release.Namespace $jwtName) -}}
{{- if not $jwtExisting }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $jwtName }}
  labels:
    {{- include "fuel-system.labels" . | nindent 4 }}
type: Opaque
data:
  secret: {{ .Values.secrets.jwt.secret | b64enc | quote }}
{{- end }}

---
{{/* ======================== SMTP ======================== */}}
{{- $smtpName := printf "%s-smtp" (include "fuel-system.fullname" .) -}}
{{- $smtpExisting := (lookup "v1" "Secret" .Release.Namespace $smtpName) -}}
{{- if not $smtpExisting }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $smtpName }}
  labels:
    {{- include "fuel-system.labels" . | nindent 4 }}
type: Opaque
data:
  host: {{ .Values.secrets.smtp.host | b64enc | quote }}
  port: {{ .Values.secrets.smtp.port | toString | b64enc | quote }}
  user: {{ .Values.secrets.smtp.user | b64enc | quote }}
  password: {{ .Values.secrets.smtp.password | b64enc | quote }}
{{- end }}
